###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: test-crud-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./db-init:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=password
      ports:
        - "8085:3306"

    webserver:
      image: nginx:alpine
      container_name: test-crud-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8083:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: test-crud-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

